### PR TITLE
[FW][FIX] public_budget: Impresión de Reporte de Expediente en expedientes.

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Ticket: 71843

Forward-Port-Of: ingadhoc/odoo-public-administration#529

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-public-administration/pull/531).

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @mav-adhoc this PR targets 17.0 and is the last of the forward-port chain containing:
* ingadhoc/odoo-public-administration#530

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by pablohmontenegro** [comment]
Cerrado sin mezclar porque en versiones posteriores está correcto el código.

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @mav-adhoc this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Pull request closed without merging**
