### PR TITLE
[FW][FIX] public_budget_tax_settlement: Devoluc Ingresos Brutos

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Ticket: 65303

Forward-Port-Of: ingadhoc/odoo-public-administration#507

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-public-administration/pull/510).

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this PR targets 16.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Pull request closed without merging**
