### PR TITLE
[FIX] public_budget: permisos al guardar un remito

### PR DESCRIPTION
**Pull request by pablohmontenegro**
Ticket: 64956
El bug se produjo por el cambio se introdujo en este pr https://github.com/ingadhoc/odoo-public-administration/pull/499

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-public-administration/pull/502).

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#503

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#503

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#503

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#503

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#503

**Pull request closed without merging**
