### PR TITLE
[FIX]public_budget: emisión reporte a fecha

### PR DESCRIPTION
**Pull request by pablohmontenegro**
Ticket: 57386

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-public-administration/pull/462).

**Review by ica-adhoc — APPROVED** [review]

**Comment by ica-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-public-administration#463

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-public-administration#463

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-public-administration#463

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-public-administration#463

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-public-administration#463

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-public-administration#463

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-public-administration#463

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-public-administration#463

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-public-administration#463

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-public-administration#463

**Pull request closed without merging**
