### PR TITLE
[IMP] public_budget: modificar nro de folios en expediente

### PR DESCRIPTION
**Pull request by pablohmontenegro**
Task: 28174
Ahora la cantidad de nro de folios en expedientes solo podrá ser modificada si se tiene permiso de administración y modo desarrollador activado.

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-public-administration/pull/499).

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#500

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#500

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#500

**Pull request closed without merging**
