### PR TITLE
[FW][FIX] sipreco_purchase: action_generate_expedient fix

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/odoo-public-administration#478

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-public-administration/pull/479).

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @pablohmontenegro this PR targets 16.0 and is the last of the forward-port chain.

To merge the full chain, say
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by vib-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @pablohmontenegro this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Pull request closed without merging**
