### PR TITLE
[FIX] public_budget: hacer que se complete por defecto la fecha en los pagos

### PR DESCRIPTION
**Pull request by pablohmontenegro**
Ticket: 60754

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-public-administration/pull/480).

**Review by ica-adhoc — APPROVED** [review]

**Comment by ica-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-public-administration#492

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-public-administration#492

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-public-administration#492

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-public-administration#492

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-public-administration#492

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-public-administration#492

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-public-administration#492

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-public-administration#492

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#492

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#492

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#492

**Pull request closed without merging**
