### PR TITLE
[FW] Revert "[FIX] public_budget:"

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
This reverts commit 0eee2ba9108eacb75eb83b961c3e1fff2c4eee20.

NOTE: We revert this commit because we have a better and generalized fix on https://github.com/ingadhoc/account-payment/pull/344

Forward-Port-Of: ingadhoc/odoo-public-administration#470

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-public-administration/pull/471).

**Comment by fw-bot-adhoc** [comment]
@zaoral cherrypicking of pull request ingadhoc/odoo-public-administration#470 failed.

stdout:
```
On branch 16.0-15.0-h-58360-kz-SodF-fw
You are currently cherry-picking commit 8b69fe5.
  (all conflicts fixed: run "git cherry-pick --continue")
  (use "git cherry-pick --skip" to skip this patch)
  (use "git cherry-pick --abort" to cancel the cherry-pick operation)

nothing to commit, working tree clean

```

stderr:
```
14:25:45.038483 git.c:439               trace: built-in: git cherry-pick 8b69fe5bbca5e45e0f92046b5d1a8ac5a959471a
14:25:45.039902 run-command.c:663       trace: run_command: git commit -n -F .git/MERGE_MSG --cleanup=verbatim --allow-empty-message
14:25:45.040554 git.c:439               trace: built-in: git commit -n -F .git/MERGE_MSG --cleanup=verbatim --allow-empty-message
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

Otherwise, please use 'git cherry-pick --skip'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-public-administration/pull/471).

**Comment by roboadhoc** [comment]
@fw-bot-adhoc I didn't know about this PR and had to retrieve its information, you may have to re-approve it as I didn't see previous commands.

**Pull request closed without merging**
