### PR TITLE
[IMP] public_budget: add field to indicate wich user approved an adva…

### PR DESCRIPTION
**Pull request by iga-adhoc**
…nce request

task: 38187

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-public-administration/pull/550).

**Comment by ica-adhoc** [comment]
@roboadhoc r+

**Comment by ica-adhoc** [comment]
@roboadhoc r-

**Review by ica-adhoc — CHANGES_REQUESTED** [review]
@iga-adhoc Faltaria cambiar la version del manifest

**Comment by ica-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
