### PR TITLE
[FW][FIX]public_budget: emisión reporte a fecha

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Ticket: 57386

Forward-Port-Of: ingadhoc/odoo-public-administration#462

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-public-administration/pull/463).

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @ica-adhoc this PR targets 16.0 and is the last of the forward-port chain.

To merge the full chain, say
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I didn't know about this PR and had to retrieve its information, you may have to re-approve it as I didn't see previous commands.

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-public-administration/pull/463).

**Comment by nicomacr** [comment]
@roboadhoc r+

**Pull request closed without merging**
