### PR TITLE
[FW][IMP] public_budget: mejora en afectaciones definitivas en transacciones

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Tarea: 30617

Forward-Port-Of: ingadhoc/odoo-public-administration#516

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-public-administration/pull/520).

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this PR targets 17.0 and is the last of the forward-port chain containing:
* ingadhoc/odoo-public-administration#519

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Pull request closed without merging**
