### PR TITLE
[FIX] sipreco_purchase: action_generate_expedient fix

### PR DESCRIPTION
**Pull request by vib-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-public-administration/pull/478).

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-public-administration#479

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-public-administration#479

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-public-administration#479

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-public-administration#479

**Pull request closed without merging**
