### PR TITLE
[ADD] sipreco_subsidy_management: tickets

### PR DESCRIPTION
**Pull request by mav-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-public-administration/pull/514).

**Comment by jcadhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@mav-adhoc @jcadhoc because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

**Comment by jcadhoc** [comment]
@roboadhoc rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Comment by roboadhoc** [comment]
@mav-adhoc @jcadhoc unable to stage: commits with multiple parents (543684d13fb2c6a099192aee643f01d438576bdd) can not be rebased, either fix the branch to remove merges or merge without rebasing

**Comment by jcadhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#521
- ingadhoc/odoo-public-administration#522

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#521
- ingadhoc/odoo-public-administration#522

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#521
- ingadhoc/odoo-public-administration#522

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#521
- ingadhoc/odoo-public-administration#522

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#521
- ingadhoc/odoo-public-administration#522

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#521
- ingadhoc/odoo-public-administration#522

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#521
- ingadhoc/odoo-public-administration#522

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#521
- ingadhoc/odoo-public-administration#522

**Comment by jcadhoc** [comment]
@fw-bot-adhoc r+

**Comment by fw-bot-adhoc** [comment]
@jcadhoc I can only do this on forward-port PRs and this is not one, see roboadhoc.

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#521
- ingadhoc/odoo-public-administration#522

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#521
- ingadhoc/odoo-public-administration#522

**Pull request closed without merging**
