### PR TITLE
[FW][FIX] public_budget: new compute methods for supplier_id and lines_id

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Ticket: 62156

Forward-Port-Of: ingadhoc/odoo-public-administration#491

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-public-administration/pull/496).

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral this PR targets 16.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Review by pablohmontenegro — APPROVED** [review]

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Pull request closed without merging**
