### PR TITLE
[FIX] sipreco: helpdesk_ticket_perm

### PR DESCRIPTION
**Pull request by mav-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-public-administration/pull/523).

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#524

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#524

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#524

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#524

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#524

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#524

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#524

**Pull request closed without merging**
