### PR TITLE
[FW][FIX] public_budget: permiso wizard full user a wirzard preventive change position

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Ticket: 63466

Forward-Port-Of: ingadhoc/odoo-public-administration#494

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-public-administration/pull/495).

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @nicomacr cherrypicking of pull request ingadhoc/odoo-public-administration#494 failed.

stdout:
```
Auto-merging public_budget/__manifest__.py
CONFLICT (content): Merge conflict in public_budget/__manifest__.py

```

stderr:
```
13:50:58.541602 git.c:444               trace: built-in: git cherry-pick 165c8803963e5991319c2093b05c960fc0f04ab1
error: could not apply 165c880... [FIX] public_budget: permiso wizard full user a wirzard preventive change position
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by nicomacr** [comment]
@roboadhoc r+ override=ci/sipreco

**Comment by roboadhoc** [comment]
I'm sorry, @nicomacr: you are not allowed to override this status.

**Pull request closed without merging**
