### PR TITLE
[ADD] p13n_cmr: sipreco_subsidies

### PR DESCRIPTION
**Pull request by mav-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-public-administration/pull/511).

**Comment by jcadhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#534

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#534

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#534

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#534

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#534

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#534

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#534

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#534

**Pull request closed without merging**
