### PR TITLE
[FW][FIX] public_budget: crear comprobante desde transacción

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Ticket: 64385

Forward-Port-Of: ingadhoc/odoo-public-administration#497

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-public-administration/pull/498).

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral cherrypicking of pull request ingadhoc/odoo-public-administration#497 failed.

stdout:
```
Auto-merging public_budget/wizards/transaction_definitive_make_invoice.py
CONFLICT (content): Merge conflict in public_budget/wizards/transaction_definitive_make_invoice.py
Auto-merging public_budget/__manifest__.py

```

stderr:
```
13:32:44.927765 git.c:444               trace: built-in: git cherry-pick 8a0a9e7ad28d4ac0fb1f4485d02c008a560719e2
error: could not apply 8a0a9e7... [FIX] public_budget: crear comprobante desde transacción
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by zaoral** [comment]
@pablohmontenegro 
Hi Pablito, please could you check this FW.
if needed fix it and merge it.

Best Regards

**Comment by zaoral** [comment]
@pablohmontenegro ping

**Comment by roboadhoc** [comment]
@pablohmontenegro @zaoral because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by nicomacr** [comment]
@roboadhoc rebase-ff

**Comment by roboadhoc** [comment]
I'm sorry, @nicomacr: this PR is already reviewed, reviewing it again is useless.

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Comment by roboadhoc** [comment]
@pablohmontenegro @zaoral unable to stage: merge conflict

**Comment by pablohmontenegro** [comment]
pr reemplazado por https://github.com/ingadhoc/odoo-public-administration/pull/512

**Pull request closed without merging**
