### PR TITLE
[FW][IMP] public_budget: mejora en afectaciones definitivas en transacciones

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Tarea: 30617

Forward-Port-Of: ingadhoc/odoo-public-administration#516

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-public-administration/pull/519).

**Comment by fw-bot-adhoc** [comment]
This PR targets 16.0 and is part of the forward-port chain. Further PRs will be created up to 17.0.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Pull request closed without merging**
