### PR TITLE
[FIX] public_budget: permitir visualizar transacciones a usuario portal

### PR DESCRIPTION
**Pull request by pablohmontenegro**
Ticket: 61849

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-public-administration/pull/485).

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-public-administration#486

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-public-administration#486

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-public-administration#486

**Pull request closed without merging**
