### PR TITLE
[FW][ADD] sipreco_subsidy_management: tickets

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/odoo-public-administration#514

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-public-administration/pull/521).

**Comment by fw-bot-adhoc** [comment]
This PR targets 16.0 and is part of the forward-port chain. Further PRs will be created up to 17.0.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@mav-adhoc @jcadhoc this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by jcadhoc** [comment]
@roboadhoc r+

**Comment by jcadhoc** [comment]
@fw-bot-adhoc r+

**Comment by fw-bot-adhoc** [comment]
@jcadhoc I can only do this on unmodified forward-port PRs, ask roboadhoc.

**Comment by jcadhoc** [comment]
@roboadhoc rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Comment by roboadhoc** [comment]
@mav-adhoc @jcadhoc unable to stage: merge conflict

**Comment by pablohmontenegro** [comment]
Hola Mati, ¿cómo estás?, ¿por qué cerraste este pr https://github.com/ingadhoc/odoo-public-administration/pull/521?. El fp del pr que me acabas de mezclar (https://github.com/ingadhoc/odoo-public-administration/pull/542) me muestra para incorporar código de este pr que no fue mezclado.

**Pull request closed without merging**
