### PR TITLE
[FIX] public_budget: permiso wizard full user a wirzard preventive change position

### PR DESCRIPTION
**Pull request by pablohmontenegro**
Ticket: 63466

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-public-administration/pull/494).

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#495

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#495

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#495

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#495

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#495

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#495

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#495

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @nicomacr this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-public-administration#495

**Pull request closed without merging**
